[package]
name = "tiny_wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-wasm = { version = "0.42.2", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]