/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_github_salpadding_tinywasm_Natives */

#ifndef _Included_org_github_salpadding_tinywasm_Natives
#define _Included_org_github_salpadding_tinywasm_Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_github_salpadding_tinywasm_Natives
 * Method:    createInstance
 * Signature: ([B[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_github_salpadding_tinywasm_Natives_createInstance
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

/*
 * Class:     org_github_salpadding_tinywasm_Natives
 * Method:    execute
 * Signature: (ILjava/lang/String;[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_github_salpadding_tinywasm_Natives_execute
  (JNIEnv *, jclass, jint, jstring, jlongArray);

/*
 * Class:     org_github_salpadding_tinywasm_Natives
 * Method:    getMemory
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_github_salpadding_tinywasm_Natives_getMemory
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_github_salpadding_tinywasm_Natives
 * Method:    setMemory
 * Signature: (II[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_github_salpadding_tinywasm_Natives_setMemory
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     org_github_salpadding_tinywasm_Natives
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_github_salpadding_tinywasm_Natives_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
