/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_github_salpadding_wasmer_Natives */

#ifndef _Included_org_github_salpadding_wasmer_Natives
#define _Included_org_github_salpadding_wasmer_Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_github_salpadding_wasmer_Natives
 * Method:    createInstance
 * Signature: ([BJ[Ljava/lang/String;[[B)I
 */
JNIEXPORT jint JNICALL Java_org_github_salpadding_wasmer_Natives_createInstance
  (JNIEnv *, jclass, jbyteArray, jlong, jobjectArray, jobjectArray);

/*
 * Class:     org_github_salpadding_wasmer_Natives
 * Method:    execute
 * Signature: (ILjava/lang/String;[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_github_salpadding_wasmer_Natives_execute
  (JNIEnv *, jclass, jint, jstring, jlongArray);

/*
 * Class:     org_github_salpadding_wasmer_Natives
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_github_salpadding_wasmer_Natives_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
